# Generated by Django 3.1.6 on 2021-02-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255, unique=True)),
                ('user_password', models.CharField(max_length=255)),
                ('user_wallet_num', models.CharField(max_length=16)),
                ('user_sum', models.IntegerField()),
            ],
        ),
    ]
