# Generated by Django 3.1.6 on 2021-03-03 16:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20210303_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallets',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='payments.users'),
        ),
        migrations.AlterField(
            model_name='wallets',
            name='wallet_num',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='wallets',
            name='wallet_sum',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
