POST http://127.0.0.1:8000/auth/reg/

{
  "user": {
    "username": "Name",
    "password": "12345678"
  }
}
###

POST http://127.0.0.1:8000/auth/login/

{
    "username": "Name",
    "password": "12345678"
}
###

GET http://127.0.0.1:8000/wallets/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Ik5hbWUiLCJpYXQiOjE2MTY1MTY0MjMsImV4cCI6MTYxNjUxNjcyMywianRpIjoiYjhiZDIwOGItNGI2My00OTExLWE1MDQtM2ZlNjkwNmZjZjQzIiwidXNlcl9pZCI6MSwib3JpZ19pYXQiOjE2MTY1MTY0MjN9.qW845KfINGuvwJflL8mohs1Q4_WOkJ8bwfPJi6ET4z0

###

GET http://127.0.0.1:8000/wallets/
