openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /usersViewSet/:
    get:
      operationId: listUsers
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
          description: ''
      tags:
      - usersViewSet
    post:
      operationId: createUsers
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
      tags:
      - usersViewSet
  /usersViewSet/{id}/:
    get:
      operationId: retrieveUsers
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this users.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
      tags:
      - usersViewSet
    put:
      operationId: updateUsers
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this users.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
      tags:
      - usersViewSet
    patch:
      operationId: partialUpdateUsers
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this users.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
      tags:
      - usersViewSet
    delete:
      operationId: destroyUsers
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this users.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - usersViewSet
  /walletsViewSet/:
    get:
      operationId: listWallets
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Wallet'
          description: ''
      tags:
      - walletsViewSet
    post:
      operationId: createWallets
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Wallet'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Wallet'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Wallet'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Wallet'
          description: ''
      tags:
      - walletsViewSet
  /walletsViewSet/{id}/:
    get:
      operationId: retrieveWallets
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this wallets.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Wallet'
          description: ''
      tags:
      - walletsViewSet
    put:
      operationId: updateWallets
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this wallets.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Wallet'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Wallet'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Wallet'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Wallet'
          description: ''
      tags:
      - walletsViewSet
    patch:
      operationId: partialUpdateWallets
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this wallets.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Wallet'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Wallet'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Wallet'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Wallet'
          description: ''
      tags:
      - walletsViewSet
    delete:
      operationId: destroyWallets
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this wallets.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - walletsViewSet
  /transactionViewSet/:
    get:
      operationId: listTransactions
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
          description: ''
      tags:
      - transactionViewSet
    post:
      operationId: createTransactions
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Transaction'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Transaction'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
          description: ''
      tags:
      - transactionViewSet
  /transactionViewSet/{id}/:
    get:
      operationId: retrieveTransactions
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this transactions.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
          description: ''
      tags:
      - transactionViewSet
    put:
      operationId: updateTransactions
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this transactions.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Transaction'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Transaction'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
          description: ''
      tags:
      - transactionViewSet
    patch:
      operationId: partialUpdateTransactions
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this transactions.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Transaction'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Transaction'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
          description: ''
      tags:
      - transactionViewSet
    delete:
      operationId: destroyTransactions
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this transactions.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - transactionViewSet
  /users/:
    get:
      operationId: listUsers
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
      - users
    post:
      operationId: createUser
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - users
  /account/:
    get:
      operationId: listUserPersonalUses
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
      - account
  /wallets/:
    get:
      operationId: listWallets
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
      - wallets
    post:
      operationId: createWallet
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - wallets
  /transactions/:
    put:
      operationId: updateTransaction
      description: 'we get a number of source and destination wallet

        by a numbers get ids of wallets

        subtract from source wallet sum

        add to destination wallet sum

        save transaction object

        get money left by source wallet id

        return Success  + money left'
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - transactions
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        user_name:
          type: string
          maxLength: 255
        user_password:
          type: string
          maxLength: 255
        wallets:
          type: array
          items:
            type: integer
      required:
      - user_name
      - user_password
      - wallets
    Wallet:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        wallet_num:
          type: string
          maxLength: 16
        wallet_sum:
          type: integer
          minimum: 0
        user_id:
          type: integer
        user_name:
          type: string
          readOnly: true
      required:
      - wallet_num
      - wallet_sum
      - user_id
    Transaction:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        sum:
          type: integer
        source_wallet_id:
          type: integer
        destination_wallet_id:
          type: integer
      required:
      - sum
      - source_wallet_id
      - destination_wallet_id
